import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const canvas=document.querySelector('#forge-canvas');const host=document.querySelector('.hero-visual');if(!canvas||!host)throw new Error('3D host unavailable');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let renderer;try{renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'high-performance'});document.documentElement.classList.add('webgl-ready')}catch(error){console.warn('WebGL fallback active',error)}
if(renderer){renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(0,.2,8.2);const root=new THREE.Group();scene.add(root);
const metal=new THREE.MeshStandardMaterial({color:0x22282d,metalness:.96,roughness:.2});const warm=new THREE.MeshStandardMaterial({color:0x7b4218,metalness:.9,roughness:.24,emissive:0x3c1703,emissiveIntensity:.45});const dark=new THREE.MeshStandardMaterial({color:0x090b0d,metalness:.85,roughness:.3});
[[2.15,.23,0,0],[1.72,.18,Math.PI/2.4,Math.PI/8],[1.28,.16,-Math.PI/3,Math.PI/2.7],[.9,.12,Math.PI/2,Math.PI/5]].forEach((r,i)=>{const mesh=new THREE.Mesh(new THREE.TorusGeometry(r[0],r[1],32,150),i%2?warm:metal);mesh.rotation.set(r[2],r[3],i*.42);root.add(mesh)});
const cage=new THREE.Mesh(new THREE.IcosahedronGeometry(1.05,2),new THREE.MeshPhysicalMaterial({color:0x15191c,metalness:.72,roughness:.18,wireframe:true,transparent:true,opacity:.5}));root.add(cage);const core=new THREE.Mesh(new THREE.SphereGeometry(.45,48,48),new THREE.MeshStandardMaterial({color:0xffd78e,emissive:0xff7a00,emissiveIntensity:4.3,roughness:.12,metalness:.2}));root.add(core);const halo=new THREE.Mesh(new THREE.SphereGeometry(.66,36,36),new THREE.MeshBasicMaterial({color:0xff9d28,transparent:true,opacity:.09,blending:THREE.AdditiveBlending,depthWrite:false}));root.add(halo);
const orbitMat=new THREE.LineBasicMaterial({color:0xd9862f,transparent:true,opacity:.36});[[2.8,1.2,.1],[2.5,1.55,1.2],[2.25,1.8,-.9]].forEach(o=>{const curve=new THREE.EllipseCurve(0,0,o[0],o[1],0,Math.PI*2);const pts=curve.getPoints(180).map(p=>new THREE.Vector3(p.x,p.y,0));const line=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(pts),orbitMat.clone());line.rotation.set(o[2],o[2]*.45,o[2]*.8);root.add(line)});
const count=innerWidth<700?140:260;const positions=new Float32Array(count*3);for(let i=0;i<count;i++){const radius=2.4+Math.random()*2.2;const angle=Math.random()*Math.PI*2;positions[i*3]=Math.cos(angle)*radius;positions[i*3+1]=(Math.random()-.5)*3.8;positions[i*3+2]=Math.sin(angle)*radius*.5}const dustGeo=new THREE.BufferGeometry();dustGeo.setAttribute('position',new THREE.BufferAttribute(positions,3));const dust=new THREE.Points(dustGeo,new THREE.PointsMaterial({color:0xffa23f,size:.035,transparent:true,opacity:.75,blending:THREE.AdditiveBlending,depthWrite:false}));scene.add(dust);
scene.add(new THREE.HemisphereLight(0xd9e9ff,0x08090a,1.35));const key=new THREE.DirectionalLight(0xffffff,4.2);key.position.set(-3,4,5);scene.add(key);const rim=new THREE.PointLight(0xff8a21,95,14,2);rim.position.set(3,-1,3);scene.add(rim);const fill=new THREE.PointLight(0x6a8ba8,35,12,2);fill.position.set(-4,-2,2);scene.add(fill);
let mouseX=0,mouseY=0,visible=true;host.addEventListener('pointermove',event=>{const rect=host.getBoundingClientRect();mouseX=(event.clientX-rect.left)/rect.width-.5;mouseY=(event.clientY-rect.top)/rect.height-.5},{passive:true});host.addEventListener('pointerleave',()=>{mouseX=mouseY=0});const visibilityObserver=new IntersectionObserver(([entry])=>visible=entry.isIntersecting,{rootMargin:'150px'});visibilityObserver.observe(host);
function resize(){const width=host.clientWidth,height=host.clientHeight;if(canvas.width!==Math.floor(width*renderer.getPixelRatio())||canvas.height!==Math.floor(height*renderer.getPixelRatio())){renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix()}}const clock=new THREE.Clock();function frame(){requestAnimationFrame(frame);if(!visible||document.hidden)return;resize();const t=clock.getElapsedTime();if(!reduced){root.rotation.y+=((t*.12+mouseX*.42)-root.rotation.y)*.035;root.rotation.x+=((-mouseY*.2+Math.sin(t*.35)*.04)-root.rotation.x)*.035;root.position.y=Math.sin(t*.72)*.09;cage.rotation.x=t*.16;cage.rotation.y=-t*.12;dust.rotation.y=t*.025;core.scale.setScalar(1+Math.sin(t*3.2)*.035);halo.scale.setScalar(1+Math.sin(t*2.4)*.08)}renderer.render(scene,camera)}frame();window.addEventListener('resize',resize,{passive:true});window.addEventListener('pagehide',()=>{visibilityObserver.disconnect();renderer.dispose();scene.traverse(object=>{object.geometry?.dispose?.();if(object.material){const materials=Array.isArray(object.material)?object.material:[object.material];materials.forEach(material=>material.dispose?.())}})},{once:true})}